name: Nginx 配置测试

on:
  schedule:
    # 每天零点运行
    - cron: '0 0 * * *'
  workflow_dispatch:
    # 支持手动触发
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 设置Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1
        
      - name: 安装jq
        run: sudo apt-get update && sudo apt-get install -y jq
      
      - name: 运行测试
        env:
          PORT: 8080
        run: |
          chmod +x ./test.sh
          ./test.sh
        
      - name: 清理Docker环境
        if: always()
        run: |
          docker-compose down
          docker system prune -af 